### ISSUE TITLE
ModuleNotFoundError: No module named 'ximilar'

### ISSUE THREAD

**Issue by dengtianbi** [Ximilar-com/xcenternet#1]
Hi,
I installed the project according to the instructions ， but when I run the scrip:CUDA_VISIBLE_DEVICES=0 nohup python train.py --model_type centernet --model_mode simple --log_dir results_voc &> voc.out &
There is an error  occurred：

 Traceback (most recent call last):
     File "train.py", line 5, in <module>
      from xcenternet.datasets import CocoDataset, VocDataset, XimilarDataset, CustomDataset
     File "/root/.local/lib/python3.8/site-packages/xcenternet/datasets/__init__.py", line 4, in <module>
       from .ximilar_dataset import XimilarDataset
     File "/root/.local/lib/python3.8/site-packages/xcenternet/datasets/ximilar_dataset.py", line 7, in <module>
       from ximilar.client.utils.json_data import read_json_file_list
   ModuleNotFoundError: No module named 'ximilar'

**Comment by BogoK** [comment]
How did you solve the issue? Please explaine?

**Comment by liborvaneksw** [comment]
Hi, we apologize for the troubles.The class XimilarDataset was used for testing by us and it should not be here because of the dependency you've mentioned. I removed it and it should work now.
