### ISSUE TITLE
Module ximilar is missing in project

### ISSUE THREAD

**Issue by BogoK** [Ximilar-com/xcenternet#2]
Hi,
I installed the project according to the instructions ， but when I run the scrip:CUDA_VISIBLE_DEVICES=0 nohup python train.py --model_type centernet --model_mode simple --log_dir results_voc &> voc.out &
There is an error occurred：

Traceback (most recent call last):
File "train.py", line 5, in
from xcenternet.datasets import CocoDataset, VocDataset, XimilarDataset, CustomDataset
File "/root/.local/lib/python3.8/site-packages/xcenternet/datasets/init.py", line 4, in
from .ximilar_dataset import XimilarDataset
File "/root/.local/lib/python3.8/site-packages/xcenternet/datasets/ximilar_dataset.py", line 7, in
from ximilar.client.utils.json_data import read_json_file_list
ModuleNotFoundError: No module named 'ximilar'

**Comment by liborvaneksw** [comment]
Hi,
thank you for your pointing this out! 

The class XimilarDataset was used for testing by us and it should not be here because of the dependency you've mentioned. I removed it and it should work now. Please let us know in case you have any other problem!

Best regards,
Libor

**Comment by liborvaneksw** [comment]
I'm closing this issue, please let us know if you have more troubles.
